local repo = "https://github.com/birchpointswe/"

return {

  title = "santoku",

  summary = table.concat({
    "santoku is a Lua 5.1 framework for building applications end to end in one language: ",
    "a dependency-light base library, a build and release harness (toku), build-time ",
    "templates, bundling to native and WebAssembly targets, browser and server runtimes, ",
    "and libraries for sqlite, cryptography, parsing, sockets, and machine learning.",
  }),

  about = table.concat({
    "santoku is developed as a set of independently versioned Lua rocks that share one ",
    "toolchain. The documentation site is itself a santoku project, and its interactive ",
    "examples run the base library in a Lua interpreter compiled to WebAssembly.",
  }),

  lua_position = table.concat({
    "santoku targets Lua 5.1, because 5.1 is the version its platforms actually share. ",
    "LuaJIT implements 5.1 and OpenResty embeds LuaJIT, so server code, client code and ",
    "the build harness all run the same language. Compiled to WebAssembly, the 5.1 core ",
    "is smaller to embed, and its single number type sidesteps the integer and float ",
    "split introduced in 5.3, which keeps numeric values crossing the JavaScript boundary ",
    "simple. Support for newer versions is meant to come from compatibility shims layered ",
    "over the 5.1 core rather than version branches in the tree; contributions and design ",
    "ideas for that layer are welcome.",
  }),

  tabs = {
    { id = "install", label = "Install", group = "Getting started",
      desc = "provision toku with setup-toku.sh: download it, read it, run it, then verify with toku doctor",
      content = require("docs.tabs.install") },
    { id = "start-lib", label = "Getting started: a library", group = "Getting started",
      desc = "scaffold, build, test and publish a Lua rock with toku: the descriptor, templated sources, C extensions, specs, and the gh plus luarocks release chain",
      content = require("docs.tabs.start_lib") },
    { id = "start-web", label = "Getting started: a web app", group = "Getting started",
      desc = "scaffold a full-stack web app, WebAssembly client plus OpenResty server in one repository: every file toku init --web produces, the configure hook, and the dev loop",
      content = require("docs.tabs.start_web") },
    { id = "start-server", label = "Getting started: a server API", group = "Getting started",
      desc = "a JSON API with no frontend: server-side SQLite under OpenResty in WAL mode, one connection and prepared statements per nginx worker, native specs against :memory:, and the subtractive recipe from toku init --web",
      content = require("docs.tabs.start_server") },
    { id = "santoku", label = "santoku", group = "Core",
      desc = "the base library: arrays, strings, tables, functions, numbers, and fractional order keys",
      url = repo .. "lua-santoku",
      content = require("docs.tabs.santoku") },
    { id = "santoku-web", label = "santoku-web", group = "Web and servers",
      desc = "browser runtime for Lua compiled to WebAssembly: val and js interop, promise await, and batched DOM access over a command buffer",
      url = repo .. "lua-santoku-web",
      content = require("docs.tabs.web") },
    { id = "santoku-sqlite", label = "santoku-sqlite", group = "Data and machine learning",
      desc = "SQLite for Lua: prepared-statement query closures, transactions, zero-copy carray vector binds, TF/cosine search, and fully encrypted databases",
      url = repo .. "lua-santoku-sqlite",
      content = require("docs.tabs.sqlite") },
    { id = "santoku-sqlite-sync", label = "santoku-sqlite sync", group = "Data and machine learning",
      desc = "peer-to-peer sync for tables you already have: trigger-captured writes, last-writer-wins over a hybrid logical clock, transport left to the application, and two peers converging in-process with no network",
      url = repo .. "lua-santoku-sqlite",
      content = require("docs.tabs.sqlite_sync") },
    { id = "santoku-sqlite-migrate", label = "santoku-sqlite-migrate", group = "Data and machine learning",
      desc = "versioned, idempotent SQL migrations for santoku-sqlite: one function that applies missing migrations in version order, forward-only, in a single transaction",
      url = repo .. "lua-santoku-sqlite-migrate",
      content = require("docs.tabs.sqlite_migrate") },
    { id = "santoku-make", label = "santoku-make", group = "Build and test",
      desc = "the project build harness behind toku: a dependency-graph engine plus a descriptor-driven project layer for lib, bin, and web packages",
      url = repo .. "lua-santoku-make",
      content = require("docs.tabs.make") },
    { id = "santoku-cli", label = "santoku-cli", group = "Build and test",
      desc = "the toku command line: build, test, install, release, and scaffolding for santoku projects",
      url = repo .. "lua-santoku-cli",
      content = require("docs.tabs.cli") },
    { id = "santoku-test-runner", label = "santoku-test-runner", group = "Build and test",
      desc = "the spec runner behind toku test: recursive test/spec discovery, Lua-pattern file matching, per-file interpreter isolation, and the conventions for writing santoku specs",
      url = repo .. "lua-santoku-test-runner",
      content = require("docs.tabs.test_runner") },
    { id = "santoku-fs", label = "santoku-fs", group = "System and crypto",
      desc = "filesystem library: whole-file and streamed I/O, path string helpers, traversal iterators, and a POSIX C extension, all raising structured errors",
      url = repo .. "lua-santoku-fs",
      content = require("docs.tabs.fs") },
    { id = "santoku-system", label = "santoku-system", group = "System and crypto",
      desc = "process spawning and POSIX glue: fork programs or Lua functions across parallel jobs and stream their output as iterators",
      url = repo .. "lua-santoku-system",
      content = require("docs.tabs.system") },
    { id = "santoku-template", label = "santoku-template", group = "Text and templates",
      desc = "compile-once template engine: text with embedded Lua blocks rendered against an env, the engine behind .tk file expansion in the toku build harness",
      url = repo .. "lua-santoku-template",
      content = require("docs.tabs.template") },
    { id = "santoku-bundle", label = "santoku-bundle", group = "Build and test",
      desc = "bundles a Lua entry script and its dependencies into one C program compiled to a native executable or WASM via emcc",
      url = repo .. "lua-santoku-bundle",
      content = require("docs.tabs.bundle") },
    { id = "santoku-monocypher", label = "santoku-monocypher", group = "System and crypto",
      desc = "Monocypher crypto bindings: diceware passphrases, Argon2id identities, EdDSA request signing, XChaCha20-Poly1305 AEAD keys, HMAC helpers",
      url = repo .. "lua-santoku-monocypher",
      content = require("docs.tabs.monocypher") },
    { id = "santoku-matrix", label = "santoku-matrix", group = "Data and machine learning",
      desc = "typed numeric vectors, dense and sparse matrices, bit matrices, and top-k retrieval: the C data layer under santoku search and ML",
      url = repo .. "lua-santoku-matrix",
      content = require("docs.tabs.matrix") },
    { id = "santoku-learn", label = "santoku-learn", group = "Data and machine learning",
      desc = "machine learning toolkit: n-gram tokenization, gazetteer matching, booleanization, spectral embeddings, ridge regression, calibrated decisions, and ANN retrieval",
      url = repo .. "lua-santoku-learn",
      content = require("docs.tabs.learn") },
    { id = "santoku-learn-llama", label = "santoku-learn-llama", group = "Data and machine learning",
      desc = "llama.cpp binding: gguf model embeddings as dense fvec codes for the santoku-learn pipeline, plus a minimal raw and chat text generator",
      url = repo .. "lua-santoku-learn-llama",
      content = require("docs.tabs.learn_llama") },
    { id = "santoku-lpeg", label = "santoku-lpeg", group = "Text and templates",
      desc = "parsing and text transformation helpers built on a vendored LPeg: JSON field streaming, HTML scanning, injection, minification, and a subsequence-safe comment stripper",
      url = repo .. "lua-santoku-lpeg",
      content = require("docs.tabs.lpeg") },
    { id = "santoku-http", label = "santoku-http", group = "Web and servers",
      desc = "transport-agnostic HTTP client front end: retry with jittered backoff, cancellation, query params, and request/response hooks over a pluggable socket backend",
      url = repo .. "lua-santoku-http",
      content = require("docs.tabs.http") },
    { id = "santoku-resty", label = "santoku-resty", group = "Web and servers",
      desc = "OpenResty glue: santoku-flavored wrappers over lua-resty HTTP clients, RSA JWT verification with JWK to PEM, and WebSocket client and server objects",
      url = repo .. "lua-santoku-resty",
      content = require("docs.tabs.resty") },
    { id = "santoku-socket", label = "santoku-socket", group = "Web and servers",
      desc = "HTTP(S) client: blocking fetch, cancelable request/await handle, and millisecond sleep over LuaSocket and LuaSec",
      url = repo .. "lua-santoku-socket",
      content = require("docs.tabs.socket") },
    { id = "santoku-mustache", label = "santoku-mustache", group = "Text and templates",
      desc = "mustache template rendering in C: compile once, render Lua values to strings, with sections, partials, and dedent",
      url = repo .. "lua-santoku-mustache",
      content = require("docs.tabs.mustache") },
    { id = "santoku-markdown", label = "santoku-markdown", group = "Text and templates",
      desc = "Markdown to HTML rendering: a C binding to Sundown exposing a single to_html function",
      url = repo .. "lua-santoku-markdown",
      content = require("docs.tabs.markdown") },
  },

}
