local fs = require("santoku.fs")
local str = require("santoku.string")
local arr = require("santoku.array")
local err = require("santoku.error")
local ids = require("docs.ids")

local order = {
  "toku-setup",
  "toku-project",
  "tk-templates",
  "santoku-primitives",
  "santoku-wasm",
  "santoku-reference",
}

local artifacts = {
  [""] = true,
  ["llms.txt"] = true,
  ["llms-full.txt"] = true,
  ["setup-toku.sh"] = true,
  ["skills.txt"] = true,
  ["AGENTS.md"] = true,
}

local marker = "<!-- generated by toku skills from https://santoku.dev/AGENTS.md -->"

local record = ">>> "

local function split_lines (s)
  local out, pos = {}, 1
  while true do
    local i = str.find(s, "\n", pos, true)
    if not i then
      if pos <= #s then
        arr.push(out, str.sub(s, pos))
      end
      return out
    end
    arr.push(out, str.sub(s, pos, i - 1))
    pos = i + 1
  end
end

local function parse (name, src)
  if str.sub(src, 1, 4) ~= "---\n" then
    err.error("skill does not open with a frontmatter block", name)
  end
  local close = str.find(src, "\n---\n", 4, true)
  if not close then
    err.error("skill frontmatter is never closed", name)
  end
  local fields = {}
  local head = split_lines(str.sub(src, 5, close))
  for i = 1, #head do
    local k, v = str.match(head[i], "^([%w%-]+):%s*(.-)%s*$")
    if not k then
      err.error("skill frontmatter line is not a key and value", name, head[i])
    end
    fields[k] = v
  end
  if fields.name ~= name then
    err.error("skill name does not match its directory", name, fields.name)
  end
  if not str.match(name, "^[a-z][a-z0-9%-]*$") or #name > 64 then
    err.error("skill name must be lowercase letters, digits and hyphens, at most 64", name)
  end
  if not fields.description or fields.description == "" then
    err.error("skill has no description, which is what triggers it", name)
  end
  if #fields.description > 1024 then
    err.error("skill description exceeds 1024 characters", name, #fields.description)
  end
  local body = str.sub(src, close + 5)
  local title = str.match(body, "^# ([^\n]+)\n")
  if not title then
    err.error("skill body must open with a level one heading", name)
  end
  return {
    name = name,
    title = title,
    description = fields.description,
    source = src,
    body = (str.gsub(str.sub(body, #title + 4), "^\n+", "")),
  }
end

local function anchors (content)
  local tabs, marks = {}, {}
  for i = 1, #content.tabs do
    local tab = content.tabs[i]
    tabs[tab.id] = true
    if tab.content then
      local ex = ids.example_ids(tab)
      for j = 1, #ex do
        marks[tab.id .. "#" .. ex[j]] = true
      end
    end
  end
  return tabs, marks
end

local function check_links (skill, site, tabs, marks)
  for ref in str.gmatch(skill.source, str.escape(site) .. "(/[%w%-%._#/]*)") do
    local path, frag = str.match(ref, "^/([^#]*)#?(.*)$")
    if not artifacts[path] then
      if not tabs[path] then
        err.error("skill links to a page that does not exist", skill.name, ref)
      end
      if frag ~= "" and not marks[path .. "#" .. frag] then
        err.error("skill links to an anchor that does not exist", skill.name, ref)
      end
    end
  end
end

local function load (opts)
  local out = {}
  local tabs, marks = anchors(opts.content)
  for i = 1, #order do
    local name = order[i]
    local fp = fs.join(opts.root_dir, "res/skills", name, "SKILL.md")
    local skill = parse(name, opts.readfile(fp))
    if str.find(skill.source, "\n" .. record, 1, true) then
      err.error("skill contains a line that would be read as a record separator", name)
    end
    check_links(skill, opts.site, tabs, marks)
    arr.push(out, skill)
  end
  return out
end

local function render_pack (skills)
  local out = { "santoku-skills 1\n" }
  for i = 1, #skills do
    arr.push(out, record, skills[i].name, "\n", skills[i].source)
  end
  return arr.concat(out)
end

local function demote (body)
  local ls = split_lines(body)
  local fenced = false
  for i = 1, #ls do
    if str.match(ls[i], "^```") then
      fenced = not fenced
    elseif not fenced and str.match(ls[i], "^#+ ") then
      ls[i] = "#" .. ls[i]
    end
  end
  return arr.concat(ls, "\n")
end

local function render_agents (skills, content, site)
  local out = { marker, "\n\n# ", content.title, "\n\n> ", content.summary, "\n\n" }
  arr.push(out,
    "Guidance for agents working in a santoku or toku project. Each section below is one ",
    "santoku skill, carrying the procedure and the mistakes that are made without it. The ",
    "full API reference, every documented module with working examples, is ", site,
    "/llms-full.txt.\n\n")
  arr.push(out, "## Lua version\n\n", content.lua_position, "\n\n")
  arr.push(out, "## Contents\n\n")
  for i = 1, #skills do
    arr.push(out, "- ", skills[i].title, ": ", skills[i].description, "\n")
  end
  for i = 1, #skills do
    local skill = skills[i]
    arr.push(out, "\n## ", skill.title, "\n\n", skill.description, "\n\n",
      demote(skill.body), "\n")
  end
  return arr.concat(out)
end

return {
  order = order,
  marker = marker,
  record = record,
  load = load,
  render_pack = render_pack,
  render_agents = render_agents,
}
